# Generated by Django 3.2 on 2021-08-02 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    def artist_taylor_swift(apps, schema_editor):
        """
        Función para unir distintos proyectos de nombre Successfee y Caja.
        """
        Album = apps.get_model('swift_lyrics', 'Album')
        Artist = apps.get_model('swift_lyrics', 'Artist')
        # Create Artist 
        taylor_swift = Artist.objects.create(
            name="Taylor Swift", first_year_active=2003
        )
        # Set Taylor Swift as Artist for every existing Album
        Album.objects.update(artist=taylor_swift)

    dependencies = [
        ('swift_lyrics', '0003_auto_20210802_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, help_text="Artist name - can alternatively use 'id' field set to id of existing artist when creating new lyrics", unique=True)),
                ('first_year_active', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(help_text='Artist', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='swift_lyrics.artist'),
        ),
        migrations.RunPython(artist_taylor_swift, migrations.RunPython.noop)
    ]
