# Generated by Django 3.2 on 2021-05-30 22:47

from django.db import migrations


def forward_func(apps, schema_editor):
    Artist = apps.get_model('swift_lyrics', 'Artist')
    Album = apps.get_model('swift_lyrics', 'Album')
    # create Taylor Swift artist
    artist, _ = Artist.objects.get_or_create(name='Taylor Swift', first_year_active=2004)
    # assign Taylor Swift artist to all existent albums
    Album.objects.update(artist=artist)


class Migration(migrations.Migration):

    dependencies = [
        ('swift_lyrics', '0003_auto_20210530_0430'),
    ]

    operations = [
        migrations.RunPython(forward_func)
    ]
